config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :health_histories

  root 'pages#home'

  get '/pages/home'
  get '/pages/welcome'
  get 'pages/about'
  get 'pages/pricing'
  get 'pages/acupuncture'
  get 'pages/approach'
end

app/views/pages/about.html.erb
<% content_for :head do %>
  <title>About Laura Zanieski</title>
  <meta name="description" content="Laura has an M.S. in Acupuncture and Oriental Medicine. She also completed a certificate program of herbal studies in Shanghai Univesity of Chinese Medicine with additional training in tuina (Chinese Massage)."/>
<% end %>
<div class="container">
  <div class="static-wrapper">
    <h2 class="static-header">About Laura</h2>
    <%= image_tag "laura-mountain-portrait.jpeg", class:"laura-about-img"%>
    <p class="static-page-paragraph">Laura Zanieski was born and raised in Pennsylvania, with fond memories
      of the four distinct seasons, lightning bugs, and thunder storms.  She specifically came to
      the Pacific Northwest to study at Bastyr University.  While there she became so enchanted with
      Seattle and the surrounding area that she stayed to create a new life as she embarked on her
      second career.</p>
    <p class="static-page-paragraph">Receiving her B.S. in psychology from Allegheny College, Laura
      adored her first career as milieu therapist working with children at Western
      Psychiatric in Pittsburgh.  In the 8 years that she was there she became enthralled
      with herbal medicine and alternative therapies.  She choose to study Oriental
      Medicine because it offered the unique opportunity to combine the physical work
      of acupuncture, the depth of knowledge of the sometimes mysterious body, the
      brilliance of plant medicine, and even the nuances of spirit.  She obtained her
      M.S. in Acupuncture and Oriental Medicine in 2003.  She also completed a certificate
      program of herbal studies in Shanghai Univesity of Chinese Medicine with additional
      training in tuina (Chinese Massage).  During her time at Bastyr, Laura also
      completed an accelerated program of study from Brenneke School of Massage.
      She feels privileged to have the opportunity spend time with her patients, getting
      to know their story, unraveling the mysteries and challenges that bring them
      to her table, and creating a supportive environment for healing.</p>
    <p class="static-page-paragraph">Laura also enjoys a side career teaching yoga and Pilates.
      She started teaching at the same time that she began her acupuncture practice.
      Her yoga/Pilates knowledge along with her massage training and coupled with her
      psych experience gives her a unique perspective on being able to “read” her
      patients and to provide comprehensive treatment as well as health education.</p>
    <p class="static-page-paragraph">Laura lives in West Seattle.  She cherishes hiking, yoga and
      aerial yoga, cooking, and precious time with family and friends.  She feels that
      gives her harmony to bring to her patients.</p>
  </div>
</div>

app/views/pages/acupuncture.html.erb
<% content_for :head do %>
  <title>Principles of Acupuncture</title>
  <meta name="description" content="cupuncture is meant to create balance in the body so that it can heal itself.  The Acupuncture “prescription” of points are there to balance the constitution of the patient as well as the presenting symptoms, if there are any." />
<% end %>
<div class="container">
  <div class="static-wrapper">
    <h2 class="static-header">Guiding Principles of Acupuncture</h2>
    <blockquote class="static-page-quote">
      <p class="static-page-paragraph">“My mission in life is not merely to survive,
        but to thrive, and to do so with some passion, some compassion, some humor,
        and some style.”</p>
      <footer>Maya Angelou</footer>
    </blockquote>
    <p class="static-page-paragraph">The most common question that an acupuncturist hears when someone finds out that is what you do for a living is: What is acupuncture good for? Then comes the list we might provide:</p>
    <ul>
      <div class="row accupuncture-benefits-list">
        <div class="col-sm-6">
          <li>Pain in the body</li>
          <li>Digestive issues</li>
          <li>Insomnia/sleep issues</li>
          <li>Infertility</li>
          <li>Decreased energy</li>
          <li>Anxiety</li>
          <li>Low mood</li>
          <li>Morning sickness</li>
        </div>
        <div class="col-sm-6">
          <li>Asthma</li>
          <li>Allergies</li>
          <li>Common cold</li>
          <li>Pre- and post- surgery for improved/faster healing</li>
          <li>Surgery avoidance</li>
          <li>Creation of an inner calm</li>
          <li>Decrease of side effects of other treatments like chemo</li>
          <li>AND so much more</li>
        </div>
      </div>
    </ul>
    <p class="static-page-paragraph">That answer is then generally followed up with the statement that they have nothing wrong with them, but that they are simply curious. This sparks a conversation about the Yellow emperors Cannon wherein there is a discussion about what to charge for acupuncture. In this discussion, the Yellow Emperor states that patients will pay you as long as they feel good.  If there arises and imbalance that causes them discomfort or illness, then they will be treated without charge until the imbalance is corrected. The idea here is that acupuncture is meant to be utilized as a prophylactic treatment. One is meant to use acupuncture to create balance in their lives just like good food, exercise, and proper sleep are meant to do.</p>
    <p class="static-page-paragraph">Acupuncture is meant to create balance in the body so that it can heal itself. The Acupuncture “prescription” of points are there to balance the constitution of the patient as well as the presenting symptoms, if there are any. These points communicate with each other about how to get into the body to affect a change. Acupuncture also creates balance emotionally and spiritually…there are points for both on the body. So in a nutshell, acupuncture creates balance for body, mind and spirit. Having that balance results in a resilient healthfulness that allows you to meet the demands of life: environmental, physical, emotional, mental stressors. The balance that acupuncturists strive for is a balance of qi, the vitality of the body.  And with that balanced qi, the body is vital, and in a place to thrive, not just survive.</p>
    <h4><strong><%= Time.current.year %> Laura M. Zanieski, L</strong></h4>
  </div>
</div>

app/views/pages/approach.html.erb
<% content_for :head do %>
  <title>Laura Zanieski Acupuncture Approach</title>
  <meta name="description" content="I approach acupuncture with passion.  I routinely say that I am blessed to have the best jobs in the world. I get the great opportunity to heal people every day."/>
<% end %>
<div class="container">
  <div class="static-wrapper">
    <h2 class="static-header">My Approach</h2>
    <blockquote class="static-page-quote">
      <p class="static-page-paragraph">“The human body is the best work of art.”</p>
      <footer>Jess C. Scott</footer>
    </blockquote>
    <p class="static-page-paragraph">I approach acupuncture with passion.  I routinely
      say that I am blessed to have the best jobs in the world.  (I also teach yoga.)
      I get the great opportunity to heal people every day.  And I am blessed to observe
      the awesome puzzle of the body.  I am driven by the art of my work.  I get excited
      to look and the body and see where its needs rebalancing.  I love to interact with
      my patients, listen to them talk, observe their behaviors to understand what I can
      do to make a shift in their bodies and minds.  I was so drawn to acupuncture because
      it has within its practice the ability to heal both the body and the mind and the spirit.</p>
  </div>
</div>

app/views/pages/contact.html.erb
<div id="map"></div>
<script>
  function initMap() {}
</script>
<script src="https://maps.googleapis.com/maps/api/js"
         async defer></script>

app/views/pages/home.html.erb
<% content_for :head do %>
  <title>Laura Zanieski Acupuncture | Chinese Herbal Medicine | Tui Na</title>
  <meta name="description" content="Laura Zanieski practices acupuncture, Chinese herbal medicine, and Tui Na in Seattle. Treatments help maintain wellness, decrease stress, and alleviate pain." />
<% end %>
<div class="container-fluid" id="homepage-bg-image">
  <div class="row">
    <div class="col-xs-12	col-sm-12	col-md-12	col-lg-12 hero-text">
      <h2>Laura Zanieski <br /> Acupuncture and Chinese Herbal Therapy</h2>
      <p><a class="btn btn-lg appointment-button" href="#" role="button" data-toggle="modal" data-target="#contactModal">Make an Appointment</a></p>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-appointment-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="contactModalLabel">Make an Appointment Today!</h3>
      </div>
      <div class="modal-body modal-appointment-body">
      <h2>Please call<a href="tel:2068190238"> 206-819-0238</h2></a>
      <h2>to schedule an appointment.</h2>
      </div>
      <div class="modal-footer modal-appointment-footer">
        <button type="button" class="btn appointment-modal-button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="jumbotron jumbotron-hero">
  <div class="row">
    <div class="col-xs-12	col-sm-4 col-md-4	col-lg-4">
      <h3>Acupuncture</h3>
    </div>
    <div class="col-xs-12	col-sm-4 col-md-4	col-lg-4">
      <h3>Herbal Medicine</h3>
    </div>
    <div class="col-xs-12	col-sm-4 col-md-4	col-lg-4">
      <h3>Tui Na</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12	col-sm-12 col-md-12	col-lg-12 pitch-text">
    <p>With over a decade of experience as an Acupuncturist and Chinese Herbal Therapist, I have helped countless
    patients achieve their wellness goals and overcome disorders.</p>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12	col-sm-4 col-md-4	col-lg-4 center-icon">
      <i class="fa fa-pagelines"></i>
      <h4>Relieve Pain</h4>
      <p>Alleviate digestive issues, allergies, and asthma.</p>
    </div>
    <div class="col-xs-12	col-sm-4 col-md-4	col-lg-4 center-icon">
      <i class="fa fa-heart"></i>
      <h4>Decrease Stress</h4>
      <p>Treatments help relax your mind, spirit, and body.</p>
    </div>
    <div class="col-xs-12	col-sm-4 col-md-4	col-lg-4 center-icon">
      <i class="fa fa-sun-o"></i>
      <h4>Maintain Wellness</h4>
      <p>Address sexual dysfunction, emotional issues, and addictions.</p>
    </div>
  </div>
</div>

app/views/pages/pricing.html.erb
<% content_for :head do %>
  <title>Laura Zanieski Acupuncture Rates</title>
  <meta name="description" content="Rates are based on a client’s income so acupuncture treatments are affordable for everyone.">
<% end %>
<div class="container">
  <div class="static-wrapper">
    <h2 class="static-header">Rates</h2>
    <blockquote class="static-page-quote">
      <p class="static-page-paragraph">“Generosity is only benevolence in practice.”</p>
      <footer>Thomas Ken</footer>
    </blockquote>
    <p class="static-page-paragraph">Inspired by Confucius’ notion on benevolence, I am introducing a sliding scale.
       I feel that this is a good route to take to make treatments more accessible for all.
       There is one fee ranging from $80-$150.</p>
    <p class="static-page-paragraph">Any herbs purchased will be added onto the total for the treatment.
      Please note that the rate is chosen by the patient.  There is a sliding scale
      income guideline below for reference…it is just a reference.  If you feel that
      you cannot afford the minimum, alert me.  I am willing to work with you as I am
      committed to make acupuncture available to all.</p>
    <p class="static-page-paragraph">If you are inspired to pay above the recommended pay range, please feel free
      to do so in order to benevolently subsidize others who cannot afford the minimum. </p>
    <p class="static-page-paragraph">Note the following are only guidelines.  Certainly there are times in our lives
      when we are more financially liquid and more financially challenged.  Also, if
      you are coming for treatment with greater frequency (2+ times/month), it is
      anticipated that you might pay on the lower end of the scale.</p>
    <table class="table table-striped" id="pricing-table">
      <thead>
        <tr>
          <th>Annual Income</th>
          <th>Pay Scale</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>$0-$40,000</td>
          <td>$80-$90</td>
        </tr>
        <tr>
          <td>$40,001-$60,000</td>
          <td>$90-$110</td>
        </tr>
        <tr>
          <td>$60,001-$80,000</td>
          <td>$110-$130</td>
        </tr>
        <tr>
          <td>$80,001-$100,000</td>
          <td>$130-$150</td>
        </tr>
        <tr>
          <td>$100,000+</td>
          <td>$150+</td>
        </tr>
      </tbody>
    </table>
    <h3 class="static-header">Regularity of Treatments</h3>
    <p class="static-page-paragraph">As stated earlier, acupuncture is meant to be a prophylactic treatment.
      Ideally, one would come for treatment once or twice a month.  That said, not everyone has it in
      their budget to come on a very regular basis.  This is understandable, that is another reason why
      I provide a sliding scale.  I suggest a frequency pay scale, in that I suggest a rate on the lower
      end of the sliding scale if patients come in for 2 or more treatments a month.  This, I feel is a
      great way to instill balance for patients who are wanting regular treatments, like athletes,
      performers, singers, who rely on their bodies for optimal functionality.  It is also a way to help
      patients who are seeking frequent treatment for a period of time because of an increased need,
      maybe because of an acute injury, a surgery, or an illness.</p>
  </div>
</div>

app/views/pages/principles.html.erb
<div class="container">
  <div class="static-wrapper">
    <h2 class="static-header">Guiding Principles of Acupuncture</h2>
    <blockquote class="static-page-quote">
      <p class="static-page-paragraph">“My mission in life is not merely to survive,
        but to thrive, and to do so with some passion, some compassion, some humor,
        and some style.”</p>
      <footer>Maya Angelou</footer>
    </blockquote>
    <p class="static-page-paragraph">The most common question that acupuncturist hears
      when someone finds out that is what you do for a living is:  What is acupuncture
      good for?  Then comes the list we might provide:  pain in the body, digestive issues,
      insomnia/sleep issues, infertility, decreased energy, anxiety, low mood, morning
      sickness, asthma, allergies, common cold, pre- and post- surgery for improved/faster
      healing, to avoid surgeries, create a sense of inner calm, to decrease side effects
      of other treatments like chemo, and so much more.</p>
      <p class="static-page-paragraph">The question is then generally followed up with the statement that they
      have nothing wrong with them, but that they are simply curious.
      This sparks a conversation about the Yellow emperors
      Cannon wherein there is a discussion about what to charge for acupuncture.
      The emperors reply is that patients will pay you as long as they feel good.
      If there arises and imbalance that causes them discomfort or illness, then they
      will be treated without charge until the imbalance is corrected.  The idea here is
      that acupuncture is meant to be utilized as a prophylactic treatment.  One is
      meant to use acupuncture to create balance in their lives just like good food,
      exercise, and proper sleep are meant to do.</p>
    <p class="static-page-paragraph">Acupuncture is meant to create balance in the body
      so that it can heal itself.  The Acupuncture “prescription” of points are there
      to balance the constitution of the patient as well as the presenting symptoms,
      if there are any.  These points communicate with each other about how to get into
      the body to affect a change.  Acupuncture also creates balance emotionally and
      spiritually…there are points for both on the body.  So in a nutshell, acupuncture
      creates balance for body, mind and spirit.  Having that balance results in a
      resilient healthfulness that allows you to meet the demands of life:  environmental,
      physical, emotional, mental stressors.  The balance that acupuncturists strive for
      is a balance of qi, the vitality of the body.</p>
  </div>
</div>

app/views/pages/welcome.html.erb
<div class="container min-height-footer">
  <div class="jumbotron jumbotron-welcome">
    <% if current_user.health_history %>
      <h2 class="welcome-text">Welcome! To edit or view your Health History form </br >please click one of the buttons below: </h2>
      <%= link_to 'Edit Info', edit_health_history_path(current_user), class: "btn btn-primary" %>
      <%= link_to 'View Info', health_history_path(current_user), class: "btn btn-success" %>

    <% else %>
      <h2 class="welcome-text">Welcome! Click the button below to fill out the Health History Form:</h2>
      <%= link_to 'Start Health History Form', new_health_history_path, class: "btn btn-primary"  %>
    <% end %>
  </div>
</div>