config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :health_histories

  root 'pages#home'

  get '/pages/home'
  get '/pages/welcome'
  get 'pages/about'
  get 'pages/pricing'
  get 'pages/acupuncture'
  get 'pages/approach'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid desktop-header-padding">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/pages/home"><i class="fa fa-leaf"></i><p id="biz-name">Laura Zanieski Acupuncture</p></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/pages/home">Home</a></li>
          <li><a href="/pages/acupuncture">Acupuncture</a></li>
          <li><a href="/pages/approach">Approach</a></li>
          <li><a href="/pages/about">About Laura</a></li>
          <li><a href="/pages/pricing">Pricing</a></li>
          <% if user_signed_in? %>
            <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete, class: "log-out-nav") %></li>
            <li class="dropdown">
              <a class="dropdown-toggle caret-nav" data-toggle="dropdown" role="button" aria-expanded="false"><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'View Forms', pages_welcome_path %></li>
                <li><%= link_to 'Change Password', edit_user_registration_path %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to('Log In', new_user_session_path)  %></li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
  <% if notice %>
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4><%= notice %></h4>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-dismissible alert-danger">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4><%= alert %></h4>
    </div>
  <% end %>

  <%= yield %>
  <div class="footer">
    <h4><i class="fa fa-copyright"></i> <%= Time.now.year %> Laura M. Zanieski, LAC</h4>
  </div>
</body>
</html>